version: "3.9"

services:
  app:
    build: .
    container_name: app
    restart: always
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    container_name: appdb
    restart: always
    ports:
      - 5433:5433
    env_file:
      - .env
    volumes:
      - appdb:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_projex
    restart: always
    ports:
      - 8080:8080

volumes:
  appdb: