# Generated by Django 4.0 on 2023-06-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(blank=True, choices=[('C', 'Casa'), ('A', 'Apartamento'), ('T', 'Terreno')], max_length=2)),
                ('adress', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('size', models.DecimalField(decimal_places=2, max_digits=19)),
                ('bedrooms', models.DecimalField(decimal_places=2, max_digits=19)),
                ('availability', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
    ]
