# Generated by Django 4.0 on 2023-06-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
    ]
