# Generated by Django 4.0 on 2023-06-13 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('properties', '0005_alter_property_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
